version: '3'

services:
  jupyter:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8888:8888"
    volumes: 
      - ./notebooks:/home/jovyan/work  
    environment:
      - JUPYTER_ENABLE_LAB=yes
      - NB_UID=1000
      - NB_GID=100
      - OPENAI_API_KEY=YOUR_API_KEY
    container_name: llm_notebook